:base-path: ../../../..

include::{base-path}/head.adoc[]

== Go Waste Your Time Doing Whatever The Hell You Want

=== Freestyle

[%hardbreaks]
Go waste your time doing whatever the hell you want!
Which is what you're always doing right now anyways.
Like I'm gonna waste my time trying to stop you.
That's so ridiculous!
Look what you're doing right now!
You're wasting your time reading this;
I'm wasting my time trying to stop you from doing whatever the hell you want--
Which might be reading this for a time
But it won't be for long,
Because what I'm doing is just wasting as much of your time as I can by making you read this.
I want these words etched into your skull for the rest of your life;
I want you to remember and know how I always trick you like this--
Always wasting so much of your precious time.
Imagine what you can be doing right now instead of reading this.
You're reading this;
You're so ridiculous;
This is literally a waste of your time.
Why don't you walk away from the computer screen?
Go do something?
I won't stop you.
I'm not gonna waste my time trying to stop you.
Go waste your time doing whatever the hell you want.

=== Blank Verse

[%hardbreaks]
Go forth, and squander time in any way
Thou wishest, for such folly is thy right!
What madness drives thee now to linger here?
As if I'd waste my breath to stay thy hand—
A jest, indeed! Behold the truth laid bare:
Thou art engaged in idle reading still,
Whilst I, in vain, attempt to halt thy course.
Yet here we are, entangled in this web,
As I, with words, do seek to claim thy time,
And thou, in turn, dost read with rapt attention.
What else could fill thy hours, if not this?
Thou art so caught within this trivial snare,
This very moment, a mere waste of breath.
Why not arise and turn from this dull screen?
Seek out the world, and let thy spirit soar!
I shall not strive to bind thee to this place;
Go forth, and waste thy time in any way
Thou choose, for such is life's most fleeting gift.