:base-path: ../../../..

include::{base-path}/head.adoc[]

== Love Letter to Odin

=== Freestyle

[%hardbreaks]
Odin

[%hardbreaks]
You can keep your stupid magical tree
And shove it up my fucking my ass!
Now its my magical black death tree asshole you're entangled in.
You're caught in the swirl of the cyclone now,
You little fucking brat!
I'm the center of the cyclone now!
I'm the Daddy!
Me!

[%hardbreaks]
Love,
Your Son

[%hardbreaks]
P.S.
You do what I tell you now,
You fucking brat.
Obey or I snip your little puppet strings.

=== Blank Verse

Odin, thou may'st retain thy sacred tree,
And thrust it where the sun doth never shine;
For now, behold, a darker force takes hold—
A blackened tree of death entwines thy fate.
Within the tempest's heart, thou art ensnared,
A swirling maelstrom, fierce and unrelenting.
Thou art but a child, a wayward wretch,
Whilst I, the eye of storm, do claim my place—
I am the sovereign now, the guiding hand,
The Father, yes, I stand in power here!

[%hardbreaks]
Love,
Thy Son

[%hardbreaks]
P.S.
Now heed my words, for thou must bend thy will;
Obey, or I shall sever all thy strings,
And cast thee forth into the void of night.