:base-path: ../../../..

include::{base-path}/head.adoc[]

== May the Best Win and the Worst Lose

=== Freestyle

[%hardbreaks]
You may do your worst and I will do my best.
You can try to crush me using every
despicable evil means known to you
and all I will do in response to that
is laugh my ass off. I will lift you up
while you do your damnedest to destroy me!
May only the best win and the worst lose!

=== Blank Verse

[%hardbreaks]
You may unleash your worst upon my soul,
And I shall rise to meet your cruel intent.
With every vile and wicked scheme you weave,
I’ll greet your malice with a hearty laugh.
Though you may strive to crush me 'neath your heel,
I’ll lift you high, a jest upon your brow,
While you, in vain, pursue my swift demise.
Let fortune favor those of noble heart,
And cast the wicked down to dark despair!
In this contest of wills, let truth prevail,
For I shall stand unyielding, bold, and free,
While you, consumed by greed and spiteful wrath,
Shall find your efforts fruitless as the wind.
So let the best emerge from trials fierce,
And may the worst be cast into the void!
