:base-path: ../../../..

include::{base-path}/head.adoc[]

== To the Tree Killers Outside My Door

=== Freestyle

[%hardbreaks]
To the tree killers outside my door:
How would you like it if I killed you the way you killed those trees?
You wouldn't like it, would you?
If I ripped you to shreds, limb from limb;
If I left a pile of bloody corpses on the side of the road for the rest of my kind to admire;
If I harvested the blood and roasted your flesh!
You'd hate that wouldn't you!
If I used your bones to build a house!
You wouldn't like that!
_*GASP*_
Would you?!
Maybe you would!
You do! You do! You do delight in this!
OK! I'll do it too! My turn! Watch!

=== Blank Verse

[%hardbreaks]
To those who wield the axe with ruthless hand,
How would you feel if I, in kind, returned
The favor you bestowed upon the trees?
Would you not shudder at the thought of pain,
If I, with savage glee, tore you asunder,
Ripping your limbs from flesh, a gruesome sight?
Imagine, then, a heap of lifeless forms,
A testament to your own cruel design,
Left for the world to witness and to mourn.
What if I took your blood to quench the flames,
And roasted flesh upon the open fire?
Would you not recoil at such a fate,
As I, with callous heart, made sport of you?
And should I craft from bone a sturdy home,
Would you not writhe in horror at the thought?
Would you not tremble at the mirror’s gaze,
Reflecting back the darkness of your deeds?
Yet, perchance, you would revel in such fate!
You do! You do! You do delight in this!
Then let it be my turn to wield the knife—
Watch closely now, for I shall take my due!
With every carve, I’ll show you what you’ve wrought,
As nature’s wrath descends upon your kind!
